version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=syncuser
      - POSTGRES_PASSWORD=syncpass
      - POSTGRES_DB=syncdb
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
